export { h } from './h'
export { renderSlots } from './helpers/renderSlots'
export { createTextVnode } from './vnode'
export { getCurrentInstance } from './component'
export { inject, provide } from './apiProvide'
export { createRenderer } from './renderer'
